.github/workflows/ci-cd.yml
docs/docusaurus.config.ts

Changelog
---------
- As part of making IIaaS more user-friendly, we enable doc search in this PR
Checklist
---------

Enable Algolia search

---

.github/workflows/ci-cd.yml
hashicorp/elk/images/aws-elk.source.pkr.hcl
hashicorp/elk/instances/aws-elk.tf
hashicorp/kong-api-gateway/images/aws/aws-kong.source.pkr.hcl
hashicorp/kong-api-gateway/images/kong.build.pkr.hcl
hashicorp/kong-api-gateway/instances/alicloud/ali-kong.tf
hashicorp/kong-api-gateway/instances/aws/aws-kong.tf
hashicorp/machine-learning/images/aws-ml.source.pkr.hcl
hashicorp/machine-learning/images/mlflow-docker/aws-ml.build.pkr.hcl
hashicorp/machine-learning/instances/aws-ml.base.tf
hashicorp/machine-learning/instances/mlflow-docker/aws-ml.tf
hashicorp/react/images/aws-react.build.pkr.hcl
hashicorp/react/images/aws-react.pkr.hcl
hashicorp/react/images/aws-react.variables.pkr.hcl
hashicorp/react/instances/aws-react.tf
hashicorp/webservice/images/aws-ws.source.pkr.hcl
hashicorp/webservice/instances/aws-ws.base.tf
hashicorp/webservice/instances/basic/aws-ws.tf
hashicorp/webservice/instances/ssl/aws-ws.tf
tests/elk/images/aws-elk.packer.pkr.hcl
tests/kong-api-gateway/images/ali-kong.packer.pkr.hcl
tests/machine-learning/images/mlflow-docker/aws-ml.packer.pkr.hcl
tests/machine-learning/images/mlflow-docker/aws-ml.source.pkr.hcl
tests/react/images/aws-react.test.pkr.hcl
tests/webservice/images/aws-ws.packer.pkr.hcl

Changelog
---------
Checklist
---------

Add Packer and Terraform Linting to CI/CD

---

adaptors/screwdriver-cd/templates/kong-api-gateway-sd-template.yaml
hashicorp/kong-api-gateway/images/alicloud/ali-kong.packer.pkr.hcl
hashicorp/kong-api-gateway/images/aws/aws-kong.packer.pkr.hcl
hashicorp/kong-api-gateway/instances/alicloud/ali-kong.tf
hashicorp/kong-api-gateway/instances/aws/aws-kong.tf
hashicorp/kong-api-gateway/scripts/ali-kong-tf-init.sh
tests/kong-api-gateway/images/ali-kong.packer.pkr.hcl

Changelog
---------
Checklist
---------

Update Kong deployment script

---

hashicorp/webservice/instances/alicloud/ali-ws.tf

Changelog
---------
Checklist
---------

Register webservice to kong gateway

---

.github/workflows/ci-cd.yml
tests/kong-api-gateway/images/ali-kong.source.pkr.hcl
tests/kong-api-gateway/images/kong.build.pkr.hcl
tests/kong-api-gateway/images/run-tests.sh

Changelog
---------
Checklist
---------

Kong Terraform integration Github Action Job

---

hashicorp/react/images/ali-react.pkr.hcl

Changelog
---------
Checklist
---------

Update ubuntu image

---

hashicorp/react/instances/ali-react.tf

Changelog
---------
Checklist
---------

fix react tf script

---

hashicorp/react/instances/ali-react.tf

Changelog
---------
Checklist
---------

Support Terraform deploy region for React Deployment

---

hashicorp/react/instances/ali-react.tf
hashicorp/react/scripts/react-tf-init.sh

Changelog
---------
Checklist
---------

Add vswitch id for React development

---

hashicorp/react/instances/ali-react.tf

Changelog
---------
Checklist
---------

Set `system_disk_category` for React Development

---

docs/docs/troubleshooting.md

Changelog
---------
- 细化完善了关于如何解决"阿里云周期性删除 ECS 基础镜像"问题的相关文档，帮助用户更快地排查问题
Checklist
---------

Enhance documentation on 'updating ECS image regularly'

---

docs/docs/setup.md

Changelog
---------
Checklist
---------

Add 'AliyunDNSFullAccess' to the list of required RAM permission list in 'setup' manual

---

hashicorp/react/scripts/react-tf-init.sh

Changelog
---------
1. start Nginx 
2. save the serve log
Checklist
---------

Start Nginx and save the serve log

---

hashicorp/react/scripts/react-tf-init.sh

Changelog
---------
Checklist
---------

Fix react init script

---

hashicorp/react/instances/ali-react.tf

Changelog
---------
Checklist
---------

Refine the domain binding in React Deployment

---

hashicorp/react/instances/ali-react.tf

Changelog
---------
add bind EIP to the React Instance
Checklist
---------

Bind the EIP to the React Instance

---

hashicorp/react/instances/ali-react.tf

Changelog
---------
`alicloud_eip_address` -> `alicloud_eip_addresses`
Checklist
---------

Fix naming error

---

hashicorp/react/instances/ali-react.tf

Changelog
---------
delete create React DNS Record
Checklist
---------

Remove create React DNS Record

---

adaptors/screwdriver-cd/templates/iiaas-base-sd-template.yaml
adaptors/screwdriver-cd/templates/iiaas-ssl-sd-template.yaml
adaptors/screwdriver-cd/templates/jersey-webservice-basic-sd-template.yaml
adaptors/screwdriver-cd/templates/react-app-sd-template.yaml
adaptors/screwdriver-cd/templates/sonatype-nexus-repository-sd-template.yaml
docs/docs/webservice/screwdriver-cd-deployment.mdx
screwdriver.yaml

Changelog
---------
Checklist
---------

Change Screwdriver template name prefix from 'hashicorp-aws' to 'iiaas'

---

.github/hashicorp/webservice.auto.pkrvars.hcl
.lycheeignore
adaptors/screwdriver-cd/templates/astraios-sd-template.yaml
adaptors/screwdriver-cd/templates/spring-webservice-basic-sd-template.yaml
docs/docs/webservice/screwdriver-cd-deployment.mdx
hashicorp/common/images/aws/aws-builder.pkr.hcl
hashicorp/common/images/aws/aws-packer.pkr.hcl
hashicorp/react/images/aws/aws-react.build.pkr.hcl
hashicorp/sonatype-nexus-repository/images/aws/aws-build.pkr.hcl
hashicorp/webservice/images/aws/aws-build.pkr.hcl
hashicorp/webservice/instances/aws/ec2-tf-init.sh
screwdriver.yaml

Change Jersey to Spring webservice deployment scheme

---

adaptors/screwdriver-cd/templates/iiaas-base-sd-template.yaml
adaptors/screwdriver-cd/templates/iiaas-ssl-sd-template.yaml
adaptors/screwdriver-cd/templates/react-app-sd-template.yaml
adaptors/screwdriver-cd/templates/spring-webservice-basic-sd-template.yaml

Changelog
---------
Checklist
---------

Change the deployment tool directory name from 'hashicorp-aws' to 'immutable-infrastructure-as-a-service' for Screwdriver webservice & react templates

---

adaptors/screwdriver-cd/templates/react-app-sd-template.yaml

Changelog
---------
Checklist
---------

Fix the 'dist' drop location for React deployment in fork

---

hashicorp/common/images/aws/aws-packer.pkr.hcl

Changelog
---------
Checklist
---------

Bump packer-plugin-paion-data version

---

adaptors/screwdriver-cd/templates/react-app-sd-template.yaml

Changelog
---------
Checklist
---------

Fix fork namespace

---

adaptors/screwdriver-cd/templates/iiaas-ssl-sd-template.yaml
adaptors/screwdriver-cd/templates/kong-api-gateway-sd-template.yaml
screwdriver.yaml

Changelog
---------
Checklist
---------

Change job names from *hashicorp-aws* to *iiaas* in screwdriver.yaml

---

adaptors/screwdriver-cd/commands/install-docker/sd-command.yaml

Changelog
---------
Checklist
---------

Change install-docker command namespace from 'QubitPi' to 'paion-data'
